apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t2c-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: t2c-demo
  source:
    repoURL: https://github.com/jcroyoaun/t2c-gitops-demo.git
    targetRevision: HEAD
    path: digital-ocean
  destination:
    server: https://kubernetes.default.svc
    namespace: t2c-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - 'Replace=true'
      - '--force'
      - 'Prune=true'
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m

